"""join table

Revision ID: 879eb1fbaf7c
Revises: a3dd086c6332
Create Date: 2023-10-02 16:53:15.400385

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '879eb1fbaf7c'
down_revision = 'a3dd086c6332'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('customer_inventory_orders',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('customer_id', sa.Integer(), nullable=True),
    sa.Column('product_inventory_id', sa.Integer(), nullable=True),
    sa.Column('sales_order_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.id'], name=op.f('fk_customer_inventory_orders_customer_id_customers')),
    sa.ForeignKeyConstraint(['product_inventory_id'], ['inventory.id'], name=op.f('fk_customer_inventory_orders_product_inventory_id_inventory')),
    sa.ForeignKeyConstraint(['sales_order_id'], ['sales_orders.id'], name=op.f('fk_customer_inventory_orders_sales_order_id_sales_orders')),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('customer_inventory_orders')
    # ### end Alembic commands ###
