"""SalesOrder  Model

Revision ID: a3dd086c6332
Revises: 4a9f10b78cf1
Create Date: 2023-10-02 16:36:53.122493

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a3dd086c6332'
down_revision = '4a9f10b78cf1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('sales_orders',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('date', sa.Date(), nullable=True),
    sa.Column('order_number', sa.String(length=255), nullable=True),
    sa.Column('customer_id', sa.Integer(), nullable=True),
    sa.Column('product_inventory_id', sa.Integer(), nullable=True),
    sa.Column('quantity', sa.Integer(), nullable=True),
    sa.Column('amount', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.id'], name=op.f('fk_sales_orders_customer_id_customers')),
    sa.ForeignKeyConstraint(['product_inventory_id'], ['inventory.id'], name=op.f('fk_sales_orders_product_inventory_id_inventory')),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('sales_orders')
    # ### end Alembic commands ###
